services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    restart: unless-stopped
    environment:
      SERVER_NAME: "${SERVER_NAME:-localhost}, php:80"
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      DATABASE_URL: mysql://${MARIADB_USER:-local}:${MARIADB_PASSWORD:-local}@database:3306/${MARIADB_DATABASE:-local}?charset=utf8mb4
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}:${HTTPS_PORT:-443}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      SYMFONY_VERSION: ${SYMFONY_VERSION:-}
      STABILITY: ${STABILITY:-stable}
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./public:/app/public
      - ./certs:/certs:ro

  frankenphp:
    # image: dunglas/frankenphp # Официальный образ FrankenPHP
    build:
      context: .
      target: frankenphp_dev  
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost}
      # CADDY_HTTPS: "on"  # Включает автоматическую генерацию сертификатов для HTTPS
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - .:/app  # Монтируем папку public Symfony
      - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile
      - ./certs:/certs:ro
    depends_on:
      - php

  database:
    image: mariadb:10.6.21
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ${MARIADB_DATABASE:-local}
      MARIADB_USER: ${MARIADB_USER:-local}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-local}
    volumes:
      - database_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_HOST=database
      - PMA_USER=local
      - PMA_PASSWORD=local

volumes:
  caddy_data:
  caddy_config:
  database_data:
